spring:
  profiles:
    active:
    - dev
  application.name: iotrobot
  datasource:
    url: jdbc:mysql://localhost:3306/sensor_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: reader
    password: secretpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      enabled: false

