spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate.SQL]': DEBUG
